dependencies {
    implementation project(':model')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'com.auth0:java-jwt:4.4.0'
    implementation 'com.auth0:jwks-rsa:0.22.1'
    testImplementation 'com.h2database:h2'
    testImplementation 'org.mockito:mockito-core:5.10.0'
}

application {
    mainClass = 'messagingservice.MessagingServiceApplication'
}
